### ISSUE TITLE
Translate does unk replacement from the wrong dictionary

### ISSUE THREAD

**Issue by antspy** [OpenNMT/OpenNMT-py#338]
Hello, 

In the translator, with the option replace_unk set to true, unk token in the translation are replaced with the token in the source corresponding to the highest attention. The problem is that in a lot of cases also the source token will be unk (for example a person's name will probably be unk both in the source and the target language vocabulary).

Is this the intended behavior? My understanding was that we should put the actual word from the source sentence instead. 

I was looking into it to try to fix it, but the problem is that all source sentences are given as onmt.IO.ONMTDataset objects, which do not retain the information about the words they replaced with unk during preprocessing, so it's not clear how to access the required words at translation time. What do you think?

**Comment by Henry-E** [comment]
Did you preprocess your data with the `-dynamic_dict -share_vocab` options?

**Comment by antspy** [comment]
Hi!

No I didn't.. since by default that is off I did not think of changing it.

**Comment by Henry-E** [comment]
Yeh there's not great documentation on the new features yet. Also just to be sure, you're using `-copy_attn` during training

**Comment by antspy** [comment]
Alright, thank you!

So I should always run with dynamic_dict share_vocab and copy_attn set to True, correct?

**Comment by Henry-E** [comment]
Run the preprocess.py script with dynamic_dict and share_vocab. Then with train.py use `-copy_attn` and possibly `-copy_attn_force` depending on what your input data looks like. @sebastianGehrmann might have a better idea if there's anything else you need to change from the defaults to get `-replace_unk` working correctly.

**Comment by sebastianGehrmann** [comment]
Theoretically you should not need to train with `-copy_attn` for `-replace_unk`. I think this could actually a bug since we want the actual source word and not the `self.fields["src"].vocab.itos` version that could also be UNK. Let me look into this

**Comment by srush** [comment]
Yeah, this is actually incorrect advice. -replace_unk is a different mode than -copy_attn. 

@sebastianGehrmann notes correctly that we should fix this. 

The --copy_attn is a different approach that you could try instead if you have lots of copied words.

**Comment by Henry-E** [comment]
Ah ok. I was making the perhaps mistaken assumption that the replace unk option was linked to Abigail See summarisation paper which can handle UNKs in the source sequence by using the pointer network / copy attention.

**Comment by antspy** [comment]
Thank you for your answers :) At the moment I implemented a dirty hack to do actual word replacement.

In general, do you suggest preprocessing the files with dynamic dict and share_vocab? I am not sure what there options do, but if they improve the results I will use them :)

**Comment by moonlightlane** [comment]
I thought the option dynamic_dict is necessary for copy_attn? Since copy mechanism needs to figure out the alignment in the input sequence, and dynamic_dict takes care of that. (*I think*)

**Comment by srush** [comment]
Sorry, I lost this thread. Is there still a bug here?

**Comment by sriniiyer** [comment]
Yes, this bug still exists.

**Comment by zhongzho** [comment]
Hi all, is there progress in this thread, I face the same issue too, tried adding in -dynamic_dict and -share_vocab, and -copy_attn, but NMT still does not translate the name entities right, hope to find solution soon. Let me know when there is progress! Thanks!

**Comment by carolscarton** [comment]
Hi all, I am also facing the same issue here. Please, let me know if you have a solution for that. Thanks a lot! Meanwhile, @antspy could you share your "dirty hack"? :)

**Comment by antspy** [comment]
@carolscarton Hi, it's pretty ugly really. I pass to the translate function also the original string; then I access the attention values returned from the translator, compute the maxIndex, and replace it with the word at the index in the original string. Something like

```
            for pred_sents, gold_sent, pred_score, gold_score, src_sent in z_batch:
                n_best_preds = [pred for pred in pred_sents[:translate_options.n_best]]
                if replace_unk_hack and is_source_file:
                    original_line = next(lines_iterator).split(' ')
                    for pred in n_best_preds:
                        for idx_tok, tok in enumerate(pred):
                            if tok == '<unk>':
                                _, maxIndex = attn[0][0][idx_tok].max(0)
                                pred[idx_tok] = original_line[maxIndex[0]]
```

**Comment by carolscarton** [comment]
@antspy Thanks for sharing it :) sorry, I am not familiar with the code and I may ask some rather simplistic/stupid questions: 
- where does line_iterator como from? I think it is some kind of data structure with the source sentences on it? 
- replace_unk_hack and is_source_file are boolean variables right? Why do you need an is_source_file?

Many thanks for your help!!

**Comment by antspy** [comment]
@carolscarton So, I modified the standard translate function; I pass to it the original text string, and whether it should use the hack (so yes, replace_unk_hack is a boolean).

I usually deal with files though, so is_source_file is a boolean that indicates whether the string passed is the original sentence to be translated, or a path to a text file that contains the sentences.

If it is a source file, then lines_iterator is an iterator that reads every line of the file

```
    if replace_unk_hack and is_source_file:
        if data_generator.batch_size != 1:
            raise ValueError('For now the replace_unk_hack only works with batch size 1')
        source_file = open(source_file_path, 'r')
        lines_iterator = (line for line in source_file)
```

(Note also that I modified this function quite some time ago, so in the meanwhile the translate function may have changed significantly)

**Comment by carolscarton** [comment]
Hi Antonio! Thanks :)

**Comment by YuChunLOL** [comment]
@srush  Hello. Notify you that this is still a bug now, and this should be fixed asap since it will hugely affect the test performance. Thanks.

**Comment by srush** [comment]
Thanks for the heads up. I will look into it today.

**Comment by srush** [comment]
This should be fixed now.

**Comment by yuchenlin** [comment]
@srush  Hi, the bug seems to be still existing. I followed the steps of [attractive summarization](http://opennmt.net/OpenNMT-py/Summarization.html#), (using my own dataset). 
In other words, I used " -dynamic_dict" and "-share_vocab" in pre-processing, "-copy_attn" and "-share_embeddings" in training, and finally used "-replace_unk" in translation. 

However, I have the same issue with the original post, which means when my source input has unknown words, then the prediction will have the <unk> as well.

**Comment by yuchenlin** [comment]
@antspy hi, could you please provide a gist for your modified new translation files for the hack feature? I am quite lost about whereto add your codes. Thanks!

**Comment by yuchenlin** [comment]
@srush  Hi, can I understand this feature in this way:

0) In the preprocessing, you have to use 
``` -dynamic_dict -share_vocab```
1) if you are doing tasks like paraphrasing or summarization, where there are lots of same words in source and target. Then, you need to ```-copy_attn``` anyway.  However, if you are just doing translation task, then you don't have to utilize copy mechanism.
2) in the translating process, then you can work with ```replace_unk``` now. When your input source sentences have unknown words, the prediction target will copy that unknown words.
