### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 48: ordinal not in range(128)

### ISSUE THREAD

**Issue by supriyalk** [OpenNMT/OpenNMT-py#78]
When I run the translate.py step of the tutorial, I get the following error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 48: ordinal not in range(128)

Any idea how to fix this error?

**Comment by shuoyangd** [comment]
This should have been fixed by 4087c46. Are you on the latest head?

**Comment by rhebok** [comment]
I ran into the same problem and changed the line 114 to `outF.write(" ".join(predBatch[b][0]).decode('utf-8') + '\n')`, and it worked. Try it out.

**Comment by shuoyangd** [comment]
Oh @rhebok you're right. I missed that spot because I was translating into English so I don't have encoding problems on the target side. I'll fix that.

**Comment by rhebok** [comment]
@shuoyangd cool, thx! Glad that I can help

**Comment by guillaumekln** [comment]
Do you confirm [this PR](https://github.com/OpenNMT/OpenNMT-py/pull/79) fixes this issue?

**Comment by shuoyangd** [comment]
@guillaumekln I cannot reproduce this problem either w/ Python2 and Python3 yet. But I don't think that PR is a Python3-compatible fix. See [here](https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error).

**Comment by shuoyangd** [comment]
Ah, think I got it -- the bug only occurs if you train the model with Python2.

Will submit another compatible PR shortly.

**Comment by shuoyangd** [comment]
I worked on this a little bit over the weekend it's harder than I'd initially thought ... because to fully resolve the problem one has to make the model serialization part Python 2 and 3 fully compatible as well, which involves much more effort than I was originally planning to make. But will keep working on that slowly (along with other stuff I'm paid to work on).

I would say for the moment stick with the fix in #79 for Python 2 users, but I won't really support merging it because in Python 3 `string` objects no longer have `decode` method, so it will crash what used to run out-of-box for Python 3 users.

**Comment by rhebok** [comment]
@shuoyangd Thank you so much for your work! Does it mean that we'd better switch to Python 3 instead so that probably the problem shall go away?

**Comment by shuoyangd** [comment]
@rhebok Yes if you train your model with Python 3 and decode either with Python 2 or Python 3 you will no longer have this problem.

BTW seems like @srush et al. pushed a bunch of new features. Not sure if these commits ever attempted to resolve this issue.

**Comment by srush** [comment]
Hmm, I don't think I fixed this. Will try to train a py2 model.

**Comment by gladuo** [comment]
@guillaumekln Maybe @shuoyangd was right. Although [this PR](https://github.com/OpenNMT/OpenNMT-py/pull/79) fix the problem in py2.7.13, It might cause the py3 crash problem, may need a better plan for whole project compatible in both 2 and 3.

**Comment by srush** [comment]
I think this is fixed now. Will add a new issue to have checks that it is 2/3 compatible.

**Comment by nickjmatthews** [comment]
Hi, I experienced this problem with python 2.7.12  and pytorch 0.2

```
Traceback (most recent call last):
  File "translate.py", line 176, in <module>
    main()
  File "translate.py", line 122, in main
    for i in predBatch[b][0]]) + '\n')
  File "/home/ubuntu/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
```

Any idea what's wrong?

**Comment by svishnu88** [comment]
HI , I am trying the latest version of torchtext , but still facing the same issue. Any idea how to fix this.
