### ISSUE TITLE
got an error when translate  a GRU -brnn model

### ISSUE THREAD

**Issue by gladuo** [OpenNMT/OpenNMT-py#86]
```
/Users/ChaiDuo/.virtualenvs/pytorch/bin/python /Users/ChaiDuo/Code/Project/OpenNMT-py/translate.py
Traceback (most recent call last):
  File "/Users/ChaiDuo/Code/Project/OpenNMT-py/translate.py", line 162, in <module>
    main()
  File "/Users/ChaiDuo/Code/Project/OpenNMT-py/translate.py", line 109, in main
    tgtBatch)
  File "/Users/ChaiDuo/Code/Project/OpenNMT-py/onmt/Translator.py", line 268, in translate
    pred, predScore, attn, goldScore = self.translateBatch(src, tgt)
  File "/Users/ChaiDuo/Code/Project/OpenNMT-py/onmt/Translator.py", line 117, in translateBatch
    encStates = (self.model._fix_enc_hidden(encStates[0]),
  File "/Users/ChaiDuo/Code/Project/OpenNMT-py/onmt/Models.py", line 166, in _fix_enc_hidden
    return h.view(h.size(0) // 2, 2, h.size(1), h.size(2)) \
RuntimeError: dimension 2 out of range of 2D tensor at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensor.c:24

Process finished with exit code 1
```

got an error when translate  a GRU -brnn model

**Comment by rhebok** [comment]
Almost the same here, I was doing a English-Chinese translation, but this problem happens w/ or w/o brnn for me ：(
```python
Traceback (most recent call last):
  File "translate.py", line 160, in <module>
    main()
  File "translate.py", line 105, in main
    tgtBatch)
  File "/home/NTTDOCOMO/zhongy/OpenNMT-py/onmt/Translator.py", line 264, in translate
    src, tgt, indices = dataset[0]
  File "/home/NTTDOCOMO/zhongy/OpenNMT-py/onmt/Dataset.py", line 60, in __getitem__
    align_right=False, include_lengths=True, dtype=self._type)
  File "/home/NTTDOCOMO/zhongy/OpenNMT-py/onmt/Dataset.py", line 29, in _batchify
    lengths = [x.size(0) for x in data]
RuntimeError: dimension 0 out of range of 0D tensor at /b/wheel/pytorch-src/torch/lib/TH/generic/THTensor.c:24
```

**Comment by mattiadg** [comment]
I fixed the problem here: https://github.com/mattiadg/OpenNMT-py/commit/fed29911bfab8ea0cad1d97b6448c2d73b4982ec
but that was before the merge of #66.

**Comment by gladuo** [comment]
@mattiadg Seems nice, but I think both brnn and GRU have some problems, and only `fed2991` have not solved my problem.

**Comment by mattiadg** [comment]
Can you tell me what have you done? I ran a training with 
'''bash
python train.py -data data/example.train.pt  -layers 1 -save_model model.bi -log_interval 50 -gpus 2 -rnn_type GRU -brnn
'''
And then the translation does not produce errors

**Comment by gladuo** [comment]
@mattiadg thx.
default layers and log_interval, using your code, and got
```
Traceback (most recent call last):
  File "/Users/ChaiDuo/Code/Git/mattiadg/OpenNMT-py/translate.py", line 162, in <module>
    main()
  File "/Users/ChaiDuo/Code/Git/mattiadg/OpenNMT-py/translate.py", line 109, in main
    tgtBatch)
  File "/Users/ChaiDuo/Code/Git/mattiadg/OpenNMT-py/onmt/Translator.py", line 281, in translate
    pred, predScore, attn, goldScore = self.translateBatch(src, tgt)
  File "/Users/ChaiDuo/Code/Git/mattiadg/OpenNMT-py/onmt/Translator.py", line 183, in translateBatch
    Variable(input, volatile=True), decStates, context, decOut)
  File "/Users/ChaiDuo/.virtualenvs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/ChaiDuo/Code/Git/mattiadg/OpenNMT-py/onmt/Models.py", line 155, in forward
    emb_t.squeeze(0), rnn_output, attn_output
TypeError: 'NoneType' object is not callable
```
not sure what is the problem...

**Comment by mattiadg** [comment]
Can you give me the commands you used for training and for translations so that I can try to replicate the error?

**Comment by gladuo** [comment]
@mattiadg I just changed [code](https://github.com/mattiadg/OpenNMT-py/blob/master/onmt/Models.py#L158) to `except (AttributeError, TypeError), e:` and everything goes fine...

I use `python train.py -data xxx -save_model xxx -gpus 0 1 2 3 -rnn_type GRU -brnn`

Thank you.

**Comment by mattiadg** [comment]
Thanks for pointing out the problem. The last that you mentioned should not be related to GRU or brnn.
I'll give it a further look .

**Comment by falcondai** [comment]
@gladuo @mattiadg has the _original_ problem been resolved?

**Comment by gladuo** [comment]
@falcondai I think, YES.

**Comment by falcondai** [comment]
thanks, i am closing the issue. @gladuo consider to open a separate issue for your second problem if needed.

**Comment by KEMDAK** [comment]
@rhebok did you get your problem solved?

**Comment by rhebok** [comment]
@KEMDAK sort of... I switched to python 3 instead.
